
-- CREATE DATABASE

CREATE DATABASE clinic;

-- CREATE PATIENTS TABLE
CREATE TABLE patients(
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  date_of_birth DATE
);

-- CREATE TABLE MEDICAL HISTORIES
CREATE TABLE medical_histories(
 id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 admitted_at TIMESTAMP, 
 patient_id INT  REFERENCES patients(id)
);

-- CREATE TABLE INVOICES
  CREATE TABLE invoices(
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  total_amount DECIMAL,
  generated_at TIMESTAMP, 
  payed_at TIMESTAMP, 
  medical_history_id INT  REFERENCES medical_histories(id)
  );

